name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.3.app/Contents/Developer

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Version
        run: swift --version

      - name: Build
        run: swift build -c release --arch arm64 --arch x86_64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: swift-bundler
          path: ./.build/apple/Products/Release/swift-bundler
